export {default as Home} from './Home'
export {default as ComicDetail} from './ComicDetail'
export {default as Chapter} from './Chapter'
export {default as ResetPassword} from './ResetPassword'
export {default as Profile} from './Profile'
export {default as Payment} from './Payment'